[package]
name = "plutus-be"
version = "0.1.0"
edition = "2021"
authors = ["Francis Masha <francismasha96@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
dotenv = "0.15.0"
